server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: searchengine
    password: OGI2Y2MxYmE2YzMyNjIx
  jpa:
    hibernate.ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog.sql
    enabled: true
    drop-first: false

logging:
  level:
    root: INFO
    org.springframework.jdbc.core.JdbcTemplate: DEBUG

indexing-settings:
  sites:
    - url:  http://www.playback.ru
      name: playback.ru
    #- url: https://www.svetlovka.ru/
    #  name: Библиотека Светловка
    - url: https://sendel.ru/
      name: sendel

jsoup-settings:
  agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.79 Safari/537.36
  referrer: https://www.google.com
  delay: 1000

search-settings:
  frequency-limit-in-percentage: 40